### ISSUE TITLE
exclude

### ISSUE THREAD

**Issue by SkipTyler** [dvlden/webpack-config#1]
https://github.com/dvlden/webpack-config/blob/1e33e6f34cb6c6e9846edce5f97543c0462c4956/webpack.config.js#L95

https://github.com/dvlden/webpack-config/blob/1e33e6f34cb6c6e9846edce5f97543c0462c4956/webpack.config.js#L128

Why do not images and fonts have an exclude?

**Comment by nnx0r** [comment]
Hello @SkipTyler, I guess you mean "why do we exclude directories there?", it's simple... 

I believe this is the right solution to this problem... So look:

If I was having some fonts and there are usually some files with `.svg` extension, they'd end up in the `images` directory.
If I had some images with `.svg` extension, they'd end up in `fonts` directory.

Now, I can't really recall from this point if they'd be in both directories (duplicated output), but either way, it's not proper place for them. So excluding those directories, in a specific `rules` would result in proper output.

**Comment by SkipTyler** [comment]
Hey. Thank you for the detailed response.
I understood.
