### ISSUE TITLE
csscomb

### ISSUE THREAD

**Issue by SkipTyler** [dvlden/webpack-config#3]
https://github.com/dvlden/webpack-config/blob/8bb1265e29fa4c81271ba18c9f89b66d32f49d3c/webpack.config.js#L55

Hey. Is it possible to configure a postcss-loader so that it would collect all the medita requests at the end of the file?
I use scss, and prescribe media requests so

```
.footer {
	height: 80px;
	display: flex;
	justify-content: space-between;
	align-items: center;
	@media screen and (max-width: 600px){
		height: 120px;
		justify-content: space-around;
		flex-direction: column-reverse;
	}
}
```

when I used the csscomb with a gulp.
Can I add this function here?

**Comment by nnx0r** [comment]
If you have your reasons to combine media queries, every package out there seems to be outdated, except this one?

https://github.com/hail2u/node-css-mqpacker

It'd be easy to add it in this config...

- First, I'd install it as dev dependency:

`yarn add -D css-mqpacker`


- Then I'd just add it to `postcss` configuration, so maybe below `autoprefixer`? 

https://github.com/dvlden/webpack-config/blob/8bb1265e29fa4c81271ba18c9f89b66d32f49d3c/webpack.config.js#L54-L71

`require('css-mqpacker')()`

Should that do it? I think so, but you must try it out and extend this yourself, as I personally don't combine media queries together. It seems interesting, but not sure if I'd be up for this.

**Comment by SkipTyler** [comment]
OK
A little later I'll try to implement. Unsubscribe, as I will! Thank you!
