### ISSUE TITLE
BrowserSync

### ISSUE THREAD

**Issue by SkipTyler** [dvlden/webpack-config#4]
https://github.com/dvlden/webpack-config/blob/8bb1265e29fa4c81271ba18c9f89b66d32f49d3c/webpack.config.js#L200

I've uncommented all the lines that are associated with _BrowserSync_

After starting _dev_, I see this message

```
[Browsersync] Watching files...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: no space left on device, watch '/home/skiptyler/webpack-config/node_modules/is-descriptor/node_modules/kind-of'
    at FSWatcher.start (fs.js:1407:26)
    at Object.fs.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:183:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/skiptyler/webpack-config/node_modules/chokidar/index.js:257:10)
    at createFsWatchInstance (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/skiptyler/webpack-config/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:183:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Flights@1.0.0 dev: `webpack-dev-server --progress --mode development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Flights@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/skiptyler/.npm/_logs/2018-06-06T15_34_26_297Z-debug.log
```
```
"browser-sync": "^2.24.4",
    "browser-sync-webpack-plugin": "^2.2.2",
```

How to solve this problem?
Thank you!

**Comment by nnx0r** [comment]
Hmmm let me think, haven't used that one in a while...

I think:

- Yes, you uncomment this code block in plugins as you already did

https://github.com/dvlden/webpack-config/blob/8bb1265e29fa4c81271ba18c9f89b66d32f49d3c/webpack.config.js#L200-L213

- Uncomment also this line and change the string value to match your own v-host domain

https://github.com/dvlden/webpack-config/blob/8bb1265e29fa4c81271ba18c9f89b66d32f49d3c/webpack.config.js#L15

- I think you should also uncomment this code block, as you won't be using it anymore

https://github.com/dvlden/webpack-config/blob/8bb1265e29fa4c81271ba18c9f89b66d32f49d3c/webpack.config.js#L155-L162

Now, I am unsure if you must setup virtual host domain, or you can simply create an server with php-cli or python or such... And point this instead of v-host domain to a variable.

For example:
```
cd ~/Sites/an-project/
php -S localhost:8000
```

**Comment by SkipTyler** [comment]
So
I have done all of the above. Did not help. It still does not work.
The only thing I did not understand.
Do I need to change the proxyDomain? Or can you leave this?
Errors still remained.

P.S. I do not use php :)

**Comment by SkipTyler** [comment]
So. I solved the problem with these errors. I ran out of file descriptors. This happens on Linux OS
There remains one more problem. Opens http: // localhost: 3000 / but can not load the page.
I have commented on this code

```
        // devServer: {
        //     contentBase: path.join(__dirname, 'src'),
        //     overlay: {
        //         warnings: true,
        //         errors: true
        //     },
        //     quiet: true
        // }, 


```
not looking at it, my site works on 8080 port

I run dev script

```
"scripts": {
    "dev": "webpack-dev-server --progress --mode development",
    "watch": "webpack --watch --progress --hide-modules",
    "build": "webpack --progress --hide-modules --mode production"
  },

```
If you run it with webpack instead of webpack-dev-server
That does not work at all
I also wrote a watch script. Nothing changed.
I also want to note that UI: http: // localhost: 3001 opens


```

  "browser-sync": "^2.24.4",
    "browser-sync-webpack-plugin": "^2.2.2",
```

I was wondering if there could be a problem with the paths.

`  match: ['**/*.html'],`

**Comment by nnx0r** [comment]
@SkipTyler I honestly cannot really remember why I did the setup for browsersync that way... I think I used it only in php projects, but `file-match` tells differently... 

I have read the docs of browser-sync and saw that we can actually use both webpack-dev-server and browser-sync by using `proxy` argument.

That is all now enabled and you can try it out...

**Comment by SkipTyler** [comment]
Yes, it works! That's cool! @dvlden  Thank you so much !
