### ISSUE TITLE
question about vendor.scss importing resources from vendor

### ISSUE THREAD

**Issue by oquirozm** [dvlden/webpack-config#5]
Hi,

Thanks a lot for putting these out there! I'm using it a lot to sketch out regular css-js components.

So I'm curious: in src/styles/vendor.scss you're importing bootstrap and font awesome from a vendor directory:
`@import 'vendor/bootstrap/main';`

Where are you aliasing the vendor directory to node_modules? The only aliasing I found in webpack.config.js was resolve.modules and resolve.alias. Yet, none of this explicitly tells to redirect from vendor/ to node_modules/

So how does webpack knows to search in node_modules when vendor is referred to in CSS files.?

**Comment by oquirozm** [comment]
oh, i think I figured out. It works just by adding 'node_modules' to resolve.modules, right? So when you import from 'vendor/bootstrap/main' and webpack doesn't finds it, it will immediately resolve to 'node_modules/bootstrap/main'.

Right? Sorry, I'm just getting a grip on webpack and I didn't understood that very well from the documentation 😅

**Comment by oquirozm** [comment]
Nevermind... My editor was hiding the /vendor directory. That's why nothing was making sense.

**Comment by nnx0r** [comment]
Sorry, wasn't active on Github recently. 
Glad you figured it out...
