### ISSUE TITLE
Image paths after build

### ISSUE THREAD

**Issue by N3los** [dvlden/webpack-config#7]
Hey guys, 

the problem i am having is after i build all the image paths are starting with `../images/` which is fine for images used in CSS but not in HTML :(

HTML image link need to be `images/` or `./images/`

If i replace line 98 in config (publicPath: '..' ) then CSS is not working.

How can i change that?

ps. Hvala Nenade :)

**Comment by nnx0r** [comment]
Hello @N3los,
Thank you for the report... 

I was aware of this problem and been prone to avoid using `img:src` in HTML.
Should now use relative paths for anything that is inside `css` build, otherwise path won't be relative.

Fixed in 6dde567

P.S. Nema na čemu.
